### ISSUE TITLE
[FEATURE] Stop LSP

### ISSUE THREAD

**Issue by mangelozzi** [boltlessengineer/NativeVim#1]
Firstly I love this project, really demystifies LSP. LSP config has always been so complicated to me, but now I see all that needs to happen, some auto commands and setup on each LSP Server!

Would be pretty cool to also show how to dettech the LSP from a buffer. I think the `:LspStop` stops all LSP, so maybe per buffer doesnt make sense and it should rather be stop LSP across the whole of Neovim (if you wanted to implement it)?

**Comment by boltlessengineer** [comment]
Thank you for your kind words. I’m glad it helped you.

Adding `:LspDetach` in terms of buffer won’t be that hard, I’m pretty sure we can make it in around 10 lines of lua code.
But I don’t think it is that much necessary to add in this project. If you want to make one by yourself, you can check out `:h vim.lsp.get_clients()` and `:h vim.lsp.buf_detach_client()`.

btw you can pass LSP client ids to `:LspStop`, so you can stop specific Language Server globally.

**Comment by mangelozzi** [comment]
Thanks for that guidance!
