### ISSUE TITLE
Autcompletion not triggered

### ISSUE THREAD

**Issue by bpingris** [boltlessengineer/NativeVim#3]
Hi!

it's not an issue with your configuration but maybe you have some extra knowledge to help me add autocompletion!

I've set up the completion like in your config, only setting the `autotrigger` option to `true`
```lua
vim.api.nvim_create_autocmd("LspAttach", {
		group = vim.api.nvim_create_augroup("UserLspAttach", { clear = false }),
		callback = function(ev)
				vim.lsp.completion.enable(true, ev.data.client_id, ev.buf, { autotrigger = true })
		end
})
```

unfortunately I don't have the completion showing up when editing files, if I call the `vim.lsp.completion.trigger` function the autocomplete works

do you know by any chance if I need to set up something else to have the autocompletion working automatically while writing in the buffer? 
this [documentation](https://neovim.io/doc/user/lsp.html#vim.lsp.completion.enable()) from neovim does not mention anything else, I think

**Comment by boltlessengineer** [comment]
tbh I have no idea why that option doesn’t work.
I’m not sure if `autotrigger` is meant to be used for enabling autocompletion.

You can create an issue in neovim repo and if so, can you mention this issue so I can follow that?

**Comment by bpingris** [comment]
I didnt take the time to fill an issue on the nvim repo, however I think the way autocomplete works is with the `.`
in my case when writing inside ts or lua files autocomplete only shows up automatically after the `.`, I guess this is based on the lsp specifications for when it should pop.

**Comment by boltlessengineer** [comment]
If the document is still lack in v0.11 release, I’ll make a issue in Neovim repo
