### ISSUE TITLE
Lsp Issue based on how vim is opened

### ISSUE THREAD

**Issue by TheLazyLemur** [boltlessengineer/NativeVim#5]
When I open Neovim using nvim . (opening a directory), the LSP doesn't get set up properly as it does when opening Neovim without the directory argument (nvim). This likely affects LSP root detection or initialisation for the current buffer.

I believe the issue is in the lsp setup here:

```lua
        root_dir = vim.fs.root(0, { "go.work", "go.mod", ".git" }),
```

setting the root dir, right before the client attaches fixes the issue.

**Comment by boltlessengineer** [comment]
Yeah `vim.fs.root` should be executed in `FileType` autocmd. I will fix that part. Thank you for noticing me!

But it should work in most cases though...
Do you still have issue when you reopen neovim after creating one of those tree file/folders?

1. open neovim in your go project folder (command argument should not matter)
2. run `:=vim.lsp.get_clients()[1].config` on command line and see if `root_dir` is registered with correct directory
